# Generated by Django 4.2.7 on 2023-11-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tag (e.g., "Offer 10%", "New", "International Shipping").', max_length=100, unique=True, verbose_name='Tag Name')),
                ('slug', models.SlugField(help_text='A slugified version of the tag name (e.g., "offer-10", "new", "international-shipping").', max_length=150, unique=True, verbose_name='Tag Slug')),
                ('is_active', models.BooleanField(default=False, help_text='Is this tag currently active and displayed on the website?', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this tag was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this tag was last updated.', verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
    ]
