# Generated by Django 4.2.7 on 2023-11-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(help_text='Discount percentage')),
                ('start_date', models.DateField(help_text='Start date of the discount')),
                ('end_date', models.DateField(help_text='End date of the discount')),
                ('is_active', models.BooleanField(default=True, help_text='Is the discount currently active?')),
            ],
        ),
    ]
