# Generated by Django 4.2.7 on 2023-11-21 08:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.CharField(choices=[('out_of_stock', 'Out of Stock'), ('upcoming', 'Upcoming'), ('in_stock', 'In Stock')], default='in_stock', max_length=20)),
                ('size', models.CharField(choices=[('S', 'Small (18cm - 6 portions)'), ('M', 'Medium (26cm - 12 portions)'), ('L', 'Large (36cm - 25 portions)')], default='S', max_length=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='products.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='product_image')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for the image.', max_length=300, null=True, verbose_name='Alt text')),
                ('default_image', models.BooleanField(default=False, help_text='Is this the default image for the product?', verbose_name='Default Image')),
                ('is_active', models.BooleanField(default=False, help_text='Is this image currently active?', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this image was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this image was last updated.', verbose_name='Updated at')),
                ('product', models.ForeignKey(help_text='The associated product for this image.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['product'],
            },
        ),
    ]
